<!--Form Information-->
<form id="ticket-form" method="post" action="<?php echo Mage::getUrl('someapi/index/sendticket') ?>">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Ticket')?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field user_name">
                        <label class="required" for="user_name"><em>*</em><?php echo $this->__('Username')?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" maxlength="255" title="Имя пользователя" value="" name="username" id="username">
                        </div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="description" style="width: 53.8%">
                    <div class="field description">
                        <label class="required" for="description"><em>*</em><?php echo $this->__('Description')?></label>
                        <div class="input-box">
                            <textarea class="input-text required-entry" maxlength="255" title="Описание проблемы" name="description" id="description"></textarea>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!--Button & Link-->
    <div class="buttons-set">
        <p class="required">
            * <?php echo $this->__('Required Fields')?>
        </p>
        <button class="button" title="Submit" type="submit">
            <span>
                <span>
                    <?php echo $this->__('Send')?>
                </span>
            </span>
        </button>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('ticket-form', true);
    //]]>
</script>